version: '3.8'

services:
  app:
    build: .
    container_name: horizon-website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
